name: Build and Release Debian package

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packaging tools
        run: sudo apt update && sudo apt install -y dpkg-dev debhelper

      - name: Prepare DEBIAN structure
        run: |
          mkdir -p build/lassar-bing-wallpaper/DEBIAN
          mkdir -p build/lassar-bing-wallpaper/usr/local/bin
          cp debian/control build/lassar-bing-wallpaper/DEBIAN/control
          cp debian/postinst build/lassar-bing-wallpaper/DEBIAN/postinst
          cp debian/postrm build/lassar-bing-wallpaper/DEBIAN/postrm
          cp lassar-bing-wallpaper.sh build/lassar-bing-wallpaper/usr/local/bin/
          chmod 755 build/lassar-bing-wallpaper/DEBIAN/postinst
          chmod 755 build/lassar-bing-wallpaper/DEBIAN/postrm

      - name: Build .deb package
        run: |
          dpkg-deb --build build/lassar-bing-wallpaper
          mv build/lassar-bing-wallpaper.deb lassar-bing-wallpaper.deb

      - name: Upload .deb to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./lassar-bing-wallpaper.deb
          asset_name: lassar-bing-wallpaper.deb
          asset_content_type: application/vnd.debian.binary-package
