name: Build and Release Lassar Bing Wallpaper

on:
  push:
    tags:
      - 'v*'  # minden v-vel kezdődő tagre automatikusan fut
  workflow_dispatch:

jobs:
  build_and_release:
    name: Build .deb and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev fakeroot

      - name: Prepare DEBIAN control file
        run: |
          mkdir -p lassar-bing-wallpaper/DEBIAN
          cat <<EOF > lassar-bing-wallpaper/DEBIAN/control
          Package: lassar-bing-wallpaper
          Version: ${GITHUB_REF_NAME#v}
          Section: utils
          Priority: optional
          Architecture: all
          Depends: curl, feh
          Maintainer: Laszlo Kardos <info@kardos-gebaeudereinigung.de>
          Description: Lassar Daily Bing Wallpaper for Openbox
           Automatically updates your Openbox wallpaper with Bing's daily image.
          EOF

      - name: Build .deb package
        run: |
          dpkg-deb --build lassar-bing-wallpaper
          ls -lh lassar-bing-wallpaper.deb

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Lassar Bing Wallpaper ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          body: |
            🌅 **Lassar Daily Bing Wallpaper for Openbox**
            
            Version: ${{ github.ref_name }}
            Built automatically with GitHub Actions.
            
            🧩 **Features**
            - Automatically downloads and sets Bing's wallpaper
            - Works perfectly with Openbox
            - Manual run support
            
            📦 **Installation**
            ```bash
            sudo dpkg -i lassar-bing-wallpaper.deb
            ```
            
            ${{
              steps.changelog.outputs.changelog
            }}
          files: |
            lassar-bing-wallpaper.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup build artifacts
        if: always()
        run: rm -rf lassar-bing-wallpaper.deb
